### ISSUE TITLE
Memory exhausted on byteserving large files

### ISSUE THREAD

**Issue by samlovescoding** [rvflorian/byte-serving-php#4]
Here is a PHP message on a url

<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1604411392 bytes) in <b>/home/XXX/domains/XXX/public_html/application/helpers/byteserve_helper.php</b> on line <b>152</b><br />

<p>Message:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1604411392 bytes)</p>

**Comment by dannyniu** [comment]
That's a common problem with a lot of PHP served file download. It can be fixed by setting "output_buffering" to "Off" in the "php.ini" configuration file, or with the `ini_set` function in the script.
